spring:
  jackson:
    serialization:
      indent_output: true
  datasource:
    url: jdbc:h2:C:\Users\logonrmlocal\Desktop\fiapcervejaria-batch;DB_CLOSE_ON_EXIT=true
    username: fiap
    password: password

file:
  path: C:\Users\logonrmlocal\Desktop\teste.txt
  input: C:\Users\logonrmlocal\Desktop\pessoas.txt